# Lecture 03의 데모

### Lecture 03의 데모에 대한 코드

참고자료: https://github.com/data-8/materials-sp22/blob/main/lec/lec04.ipynb

In [1]:
import os
from google.colab import drive

drive.mount('/content/gdrive')

%cd /content/gdrive/MyDrive/ITEC419-fa22/lec

Mounted at /content/gdrive
/content/gdrive/MyDrive/ITEC419-fa22/lec


In [2]:
from datascience import *
import numpy as np

## Numbers ##

int/int -> 결과값은 float으로 바뀐다 소숫점 15자리까지 표기, 그 뒤는 삭제

In [3]:
10/3

3.3333333333333335

In [4]:
30

30

In [5]:
10/2

5.0

In [6]:
10**3

1000

In [7]:
10**0.5

3.1622776601683795

아주 큰 수도 파이썬은 자유자재로 다룰 수 있음 
(int는 아주 큰 값도 모두 저장하지만, 실수는 소숫점 15번째자리까지만 다룸)

In [10]:
1234567**80

20949474180421801756984808716181719434452425539533262416825923726832525190804378215705056773207127310647772557070609957942170473237841985163100190918850388853324961184444861565425615733220967505249050755440465055926240447198640741954304436354833183728574856184945265998018988884811323695855664552626187645050528763717892020942817636307624488470950345258346925656600255957148397973695131819432513190314045160430152852889777700834501348040261725596236634307777725674510555779972928273558401

15번째 자리까지만 표현하므로 결과값이 0으로 나옴

In [11]:
74353362.123123123123123123123123-74353362.1231231231

0.0

int로 형변환 (그냥 계산하면 10/5=2.0)

In [12]:
int(10/5)

2

In [13]:
float(3)

3.0

In [14]:
6/4

1.5

In [15]:
6/40000

0.00015

뒤에 0을 아무리 많이 붙이더라도
6/4*10^x 의 형태로 연산이 수행됨

In [16]:
6/40000000000000000000

1.5e-19

In [18]:
x=5

In [19]:
2*x

10

In [20]:
1234123123123123123123.123124142123

1.234123123123123e+21

실수는 소순점 15번째자리까지만 정확하다

## Strings ##

In [ ]:
'Flavor'

In [22]:
Flavor=1221453251

In [23]:
'Vanila Flavor'

'Vanila Flavor'

In [24]:
123

123

In [25]:
'123'

'123'

In [26]:
print(1234)

1234


In [27]:
"Don't put an apostrophe within a single-quoted string"

"Don't put an apostrophe within a single-quoted string"

'Don't put an apostrophe within a single-quoted string' 라고 작성하면 'Don'까지만 한 스트링으로 인식되므로 문제 생김

In [28]:
'you can have "quatation" marks'

'you can have "quatation" marks'

스트링을 여닫는 따옴표와 스트링 내부의 따옴표가 다른 형태이면 써도 됨

In [29]:
hi = "hello"
hi

'hello'

In [30]:
'hello '+'student'

'hello student'

In [31]:
x='straw'
y='berry'
x+y

'strawberry'

*문자열과 스트링은 연산이 불가능하다* //
숫자를 문자열로 변형하면 문자열끼리 붙이는 연산으로 인식되어 가능 //
int('23.0')은 불가능 //
float('23.0')으로 해야함

In [32]:
3*'ha '

'ha ha ha '

In [33]:
'ha'+str(10)

'ha10'

In [34]:
int('23')+1

24

In [35]:
str(int('23')+1)

'24'

In [36]:
int(23.0)

23

## Types ##

In [37]:
type(10)

int

In [38]:
x=10

In [39]:
type(x)

int

In [40]:
x=1.0

x=1.0을 넣는 순간 원래 x=10은 없어지고 x=1.0이 됨

In [41]:
type(4.5)

float

In [42]:
type('abc')

str

In [43]:
type(Table.read_table('nba_salaries.csv'))

datascience.tables.Table

패키지.클래스.타입

In [44]:
t=Table.read_table('nba_salaries.csv')

In [45]:
t

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

In [46]:
type(True)

bool

In [47]:
abs(-5)

5

In [48]:
type(abs)

builtin_function_or_method

In [49]:
type(abs(-5))

int

type 함수를 실행하기에 앞서 인자들끼리 계산 우선 하고 type 함수 실행
1. abs(-5)
2. type(5)

In [50]:
x=abs
type(x)

builtin_function_or_method

In [51]:
x(-100)

100

In [52]:
type(x(1500))

int

## Arrays ##

In [53]:
first_four = make_array(1, 2, 3, 4)

외워두기
**굵은 텍스트**순차적으로 값이 있는걸로 make_array 함수를 쓰면 배열을 만들 수 있다

In [54]:
first_four

array([1, 2, 3, 4])

In [55]:
type(first_four)

numpy.ndarray

numpy 패키지(파이썬 패키지). array 타입이다

In [ ]:
np.average(first_four)

배열 내부의 값을 모두 더해서 평균 구함

In [56]:
np.sum(first_four)

10

In [57]:
first_four + 3

array([4, 5, 6, 7])

dimention이 다를 때는 이걸 확장한 후에 더함 // 
(3이 [3,3,3,3]이라는 배열로 바뀐 후 더해짐) //
덧셈 연산이면 3을 각 원소에 모두 더하는 의미

In [58]:
first_four*3

array([ 3,  6,  9, 12])

In [59]:
first_four**2

array([ 1,  4,  9, 16])

In [60]:
first_four

array([1, 2, 3, 4])

하지만 실제로 기존의 배열이 바뀌지는 않았다.

In [61]:
second_four=make_array(5,6,7,8)

In [62]:
first_four + second_four

array([ 6,  8, 10, 12])

In [63]:
only_three = make_array(5,6,7)

first_four + only_three //
배열의 원소 개수가 다른데 덧셈 연산을 하려면 오류 남 // 
동일하게 만들 수 있는 방법은 배열의 사이즈가 1일 때 뿐

In [64]:
only_one=make_array(5)

In [65]:
first_four+only_one

array([6, 7, 8, 9])

In [66]:
s=make_array('ha','he','ho')
s

array(['ha', 'he', 'ho'],
      dtype='<U2')

In [67]:
s.item(0)

'ha'

In [ ]:
0번째 아이템
3번째 아이템은 없으니까 s.item(3) 하면 오류남 (index outofbound)

## Columns of Tables are Arrays ##

In [68]:
nba = Table.read_table('nba_salaries.csv').where('season', 2020).drop('season')
nba.show(5)

In [69]:
warriors = nba.where('team', 'Golden State Warriors')
warriors.show(5)