# Lecture 04의 데모

### Lecture 04의 데모에 대한 코드

참고자료: https://github.com/data-8/materials-sp22/blob/main/lec/lec05.ipynb

In [2]:
import os
from google.colab import drive

drive.mount('/content/gdrive')

%cd /content/gdrive/MyDrive/ITEC419-fa22/lec

Mounted at /content/gdrive
/content/gdrive/MyDrive/ITEC419-fa22/lec


In [3]:
from datascience import *
import numpy as np

## Columns of Tables are Arrays

In [4]:
nba = Table.read_table('nba_salaries.csv').where('season', 2020).drop('season')
nba

rank | name              | position | team                  | salary
1    | Stephen Curry     | PG       | Golden State Warriors | 40231758
2    | Chris Paul        | PG       | Oklahoma City Thunder | 38506482
3    | Russell Westbrook | PG       | Houston Rockets       | 38506482
4    | John Wall         | PG       | Washington Wizards    | 38199000
5    | Kevin Durant      | SF       | Brooklyn Nets         | 38199000
6    | James Harden      | SG       | Houston Rockets       | 38199000
7    | LeBron James      | SF       | Los Angeles Lakers    | 37436858
8    | Kyle Lowry        | PG       | Toronto Raptors       | 34996296
9    | Blake Griffin     | PF       | Detroit Pistons       | 34449964
10   | Tobias Harris     | SF       | Philadelphia 76ers    | 32742000
... (518 rows omitted)

In [5]:
nba.num_columns

5

In [6]:
nba.num_rows


528

In [7]:
nba.labels

('rank', 'name', 'position', 'team', 'salary')

In [8]:
nba.where('team','Golden State Warriors	')

rank | name | position | team | salary

nba 테이블에서 team이 Golden State Warriors	인 것만 찾기

In [9]:
warriors=(nba.where('team','Golden State Warriors')
              .drop('team')
              .relabeled('salary','$'))
warriors.show(3)

salary -> $

In [10]:
warriors.select('$')

$
40231758
32742000
18539130
4464226
2177483
1964760
1897800
898310
898310
842327
... (3 rows omitted)

In [11]:
type(warriors.select('$'))

datascience.tables.Table

In [12]:
warriors.column('$')

array([40231758, 32742000, 18539130,  4464226,  2177483,  1964760,
        1897800,   898310,   898310,   842327,   654469,   350189,   350189])

이렇게 하면 배열로 뽑힘 -> numpy의 array 함수 사용 가능

In [13]:
warriors.column('$').sum()

106010951

In [14]:
np.sum(warriors.column('$'))

106010951

In [15]:
np.average(warriors.column('$'))

8154688.538461538

In [16]:
warriors.column('$').item(0)

40231758

In [17]:
suns=(nba.where('team','Phoenix Suns')
          .drop('team')
          .relabeled('salary','$'))
suns.show(3)

In [18]:
np.average(suns.column('$'))

5761373.9473684207

In [19]:
np.average(warriors.column('$'))-np.average(suns.column('$'))

2393314.5910931174

warriors팀과 suns 팀의 평균 연봉의 차이

In [20]:
np.sum(warriors.column('$'))-np.sum(suns.column('$'))

-3455154

전체 선수의 연봉 합

In [21]:
suns.num_rows

19

## Ranges

In [22]:
make_array(0,1,2,3,4,5,6)

array([0, 1, 2, 3, 4, 5, 6])

In [23]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [24]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [25]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
np.arange(0,1,0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [28]:
warriors.take(1)

rank | name          | position | $
13   | Klay Thompson | SG       | 32742000

take 는 row에 대한 것, select는 column에 대한 것

In [29]:
warriors.take(0,1,2,3,4)

rank | name                | position | $
1    | Stephen Curry       | PG       | 40231758
13   | Klay Thompson       | SG       | 32742000
60   | Draymond Green      | PF       | 18539130
223  | Kevon Looney        | PF       | 4464226
316  | Willie Cauley-Stein | C        | 2177483

In [30]:
warriors.take(np.arange(5))

rank | name                | position | $
1    | Stephen Curry       | PG       | 40231758
13   | Klay Thompson       | SG       | 32742000
60   | Draymond Green      | PF       | 18539130
223  | Kevon Looney        | PF       | 4464226
316  | Willie Cauley-Stein | C        | 2177483

In [31]:
np.sum(suns.take(np.arange(5)).column('$'))

76137832

In [32]:
warriors.select(np.arange(1,3))

name                | position
Stephen Curry       | PG
Klay Thompson       | SG
Draymond Green      | PF
Kevon Looney        | PF
Willie Cauley-Stein | C
Jordan Poole        | SG
Omari Spellman      | PF
Alen Smailagic      | PF
Eric Paschall       | PF
Damion Lee          | SG
... (3 rows omitted)

## Ways to Create a Table

### Creating a Table from Scratch

In [33]:
streets = make_array('Bancroft', 'Durant', 'Channing', 'Haste')
streets

array(['Bancroft', 'Durant', 'Channing', 'Haste'],
      dtype='<U8')

In [34]:
southside=Table().with_column('Street name',streets)
southside

Street name
Bancroft
Durant
Channing
Haste

레이블과 배열 주고 테이블 만들기

In [35]:
southside.with_column('Blocks from campus',np.arange(4))

Street name | Blocks from campus
Bancroft    | 0
Durant      | 1
Channing    | 2
Haste       | 3

In [36]:
southside

Street name
Bancroft
Durant
Channing
Haste

In [37]:
a=30

In [ ]:
a

30

In [ ]:
a='hello'

a는 기억 장소보다는 Name의 개념으로 생각할 것 // 항상 a는 새로운 object

Table()을 이용해서 empty table을 생성한 이후, with_columns()멤버 함수를 사용하여,,,

In [38]:
southside = Table().with_columns(
    'Streets', streets,
    'Blocks from campus', np.arange(4)  #새로 테이블을 만들었다. 
)
southside

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

In [39]:
southside.with_row(['Dwright',4])
southside

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

이미 있는 테이블에 행 하나 추가

In [ ]:
Table()

### Reading a Table from a File

In [ ]:
du_bois = Table.read_table('du_bois.csv')
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

**Discussion**: Which group ("CLASS") spent the highest percentage on rent?

In [ ]:
du_bois.column('RENT').max()

0.23000000000000001

In [ ]:
du_bois.where('RENT'.du_bois.column('RENT').max()).column('CLASS').item(0)

AttributeError: ignored

In [ ]:
du_bois.set_format('FOOD'.PercentFormatter)

AttributeError: ignored

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Discussion Question: NBA Salaries

In [ ]:
nba = Table.read_table('nba_salaries.csv')
nba.show(3)

**Question (a)**: Create an array containing the names of all point guards (PG) who made more than $15M.

In [ ]:
guards=nba.where('position','PG')
guards.show(3)

In [ ]:
guards.where('salary',are.above(15000000).name())

**Question (b)**: After evaluating these two expressions in order, what’s the result of the second one?

    nba.drop('position')
    nba.num_columns

In [ ]:
nba.drop('position')
nba.num_columns

6

**Question (c)**: Who gets the highest salary among non-point guard players?

**Question (d)**: Create an array containing the names of the most frequently selected players in the annual salary top.

**Question (e)**: Create an array containing the names of the most frequently selected players in the annual salary top 10.

Census

In [ ]:
full = Table.read_table('nc-est2019-agesex-res.csv')
full

SEX  | AGE  | CENSUS2010POP | ESTIMATESBASE2010 | POPESTIMATE2010 | POPESTIMATE2011 | POPESTIMATE2012 | POPESTIMATE2013 | POPESTIMATE2014 | POPESTIMATE2015 | POPESTIMATE2016 | POPESTIMATE2017 | POPESTIMATE2018 | POPESTIMATE2019
0    | 0    | 3944153       | 3944160           | 3951430         | 3963092         | 3926570         | 3931258         | 3954787         | 3983981         | 3954773         | 3893990         | 3815343         | 3783052
0    | 1    | 3978070       | 3978090           | 3957730         | 3966225         | 3977549         | 3942698         | 3948891         | 3973133         | 4002903         | 3972711         | 3908830         | 3829599
0    | 2    | 4096929       | 4096939           | 4090621         | 3970654         | 3978925         | 3991740         | 3958711         | 3966321         | 3991349         | 4020045         | 3987032         | 3922044
0    | 3    | 4119040       | 4119051           | 4111688         | 4101644         | 3981531         | 3991017         | 4005928         | 3974351         | 3982984         | 4006946         | 4033038         | 3998665
0    | 4    | 4063170       | 4063186           | 4077346         | 4121488         | 4111490         | 3992502         | 4004032         | 4020292         | 3989750         | 3997280         | 4018719         | 4043323
0    | 5    | 4056858       | 4056872           | 4064521         | 4087054         | 4131049         | 4121876         | 4004576         | 4017589         | 4035033         | 4003452         | 4008443         | 4028281
0    | 6    | 4066381       | 4066412           | 4072904         | 4074531         | 4096631         | 4141126         | 4133372         | 4017388         | 4031568         | 4048018         | 4014057         | 4017227
0    | 7    | 4030579       | 4030594           | 4042990         | 4082821         | 4084175         | 4106756         | 4152666         | 4145872         | 4030888         | 4044139         | 4058370         | 4022319
0    | 8    | 4046486       | 4046497           | 4025501         | 4052773         | 4092559         | 4094513         | 4118349         | 4165033         | 4158848         | 4042924         | 4054236         | 4066194
0    | 9    | 4148353       | 4148369           | 4125312         | 4035319         | 4062726         | 4103052         | 4106068         | 4130887         | 4177895         | 4170813         | 4053179         | 4061874
... (296 rows omitted)